application: chugo-626
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: application/static/img/favicon.ico
  
- url: /robots.txt
  static_files: static/robots.txt
  upload: application/static/robots.txt
  
- url: /static
  static_dir: application/static
  
- url: .*
  script: run.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: numpy
  version: "1.6.1"
- name: webapp2
  version: "2.5.2"